name: news_app_flutter
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  splashscreen:
  http:
  webview_flutter: 0.2.0

  cupertino_icons: ^0.1.2
  image_picker: 0.4.12+1
  firebase_auth: ^0.6.6
  connectivity: 0.4.2
  sqflite: ^1.0.0
  path_provider: ^0.4.1
  fluttertoast: ^3.0.3
  firebase_messaging: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
  - assets/newspaper.png
  - assets/login.png
  - assets/add.ico
  - assets/news_placeholder.jpg
